version: '2'
services:
    angularcampblog-app:
        image: angularcampblog
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://angularcampblog-mysql:3306/angularcampblog?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    angularcampblog-mysql:
        extends:
            file: mysql.yml
            service: angularcampblog-mysql
